#var

@baseUrl = http://localhost:3333

#check

GET {{baseUrl}}/health

###get

# @name getRooms

GET {{baseUrl}}/rooms

###create
# @name createRoom

POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "sala test",
    "description": "descrip test"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###
# @name getRoomQuestions

GET {{baseUrl}}/rooms/{{roomId}}/questions


###createQuestion
# @name createQuestion

POST {{baseUrl}}/rooms/c72f7b84-3475-48f7-9f0a-87c9b0629041/questions
Accept: application/json
Content-Type: application/json

{
    "question": "o que é vue.js e a diferenca para o angular"
}